### ISSUE TITLE
[OS X] Plugin not working properly?

### ISSUE THREAD

**Issue by DevonVille** [fdemmer/Picard-Last.fm.ng-Plugin#25] opened 2016-03-18 21:44 UTC
Hi,
I just installed the plugin,
and ran through the normal process of clustering, lookup etc.
Upon inspection of the files, there ARE new tags added - Grouping, Mood etc, 
BUT ALL of them are given an "Unknown" value.

I tried adding a new, different, API key, but that didn't seem to change much.
I'm using LastFmNg v0.14 on a MacOSX.

Help?

**Comment by fdemmer** [comment] 2016-03-25 02:18
works for me without config changes on linux.

what is the album you are trying to tag, a musicbrainz link would be ideal to try to reproduce the problem.

**Comment by DevonVille** [comment] 2016-03-29 15:38
I tried several albums/artists.
All Tom Waits' albums being among them...
How can I find the MusicBrainz link?

**Comment by fdemmer** [comment] 2016-03-29 21:21
> How can I find the MusicBrainz link?

in picard right click and show in browser

![musicbrainz picard_023](https://cloud.githubusercontent.com/assets/630975/14124255/d9514ea4-f604-11e5-856b-00055a158710.png)

or just look for the artist, choose a release group and then copy the _release_link, eg. http://musicbrainz.org/release/a2de224a-4f10-30fa-8df3-d4fcf77aab61?tport=8000

**Comment by fdemmer** [comment] 2016-03-29 21:44
this works

![musicbrainz picard_024](https://cloud.githubusercontent.com/assets/630975/14124826/f5943dbc-f607-11e5-9054-65a8c4ffc60d.png)

check in picard, menu "help - view error/debug log" for any error messages.

**Comment by DevonVille** [comment] 2016-03-30 18:53
Hmm, odd.
I just tested the plugin on Windows7, 
and it works perfectly, without any additional tinkering.
I tried Tom Waits' Blue Valentine album.
Same album (file sharing), different OS's (original files are on mac)...

Has anyone tried the plugin on MacOS?
Checking the error log in Mac, it says no tags are found (for mood, genre, etc...)

**Comment by fdemmer** [comment] 2016-03-30 22:27
i dont have a mac.

start picard in a shell and copy/paste the whole console output before adding files/an album. during start of picard, when loading the plugins there might be error output indicating what's going wrong.

**Comment by woto99** [comment] 2016-04-01 16:19
I think it's the same I posted here https://github.com/fdemmer/Picard-Last.fm.ng-Plugin/issues/22
I had found a way to bypass it by changing the os date (bringing it back to october 2015), but it's not working anymore since the last month. Plugin is working in windows7 on a secondary pc, it doesn't work in windows7 on a mac virtual machine.

**Comment by fdemmer** [comment] 2016-04-01 16:23
Are you getting the "Network request error SSL handshake failed" error?

**Comment by woto99** [comment] 2016-04-01 16:31
Yes, I'm still getting the "SSL handshake failed (QT code 6, HTTP code None)" error

**Comment by fdemmer** [comment] 2016-04-01 17:43
@iwfpm you too?

**Comment by DevonVille** [comment] 2016-04-01 20:00
Um, unsure. How can you run Picard from the shell?...
I have installed it from brew cask

**Comment by woto99** [comment] 2016-04-01 22:45
Open terminal and paste this:
cd /Applications/MusicBrainz\ Picard.app/Contents/MacOS/
./MusicBrainz\ Picard

**Comment by DevonVille** [comment] 2016-04-03 14:56
Thanks, here is the log:

Picard[32534] <Notice>: W: 17:55:27 Plugin directory '/opt/homebrew-cask/Caskroom/musicbrainz-picard/1.3.2/MusicBrainz Picard.app/Contents/Resources/plugins' doesn't exist
Picard[32534] <Notice>: E: 17:55:29 Network request error for https://musicbrainz.org/ws/2/collection: Error downloading https://CrimsonKing1497:j2UyHWtUh1YJOzmtBXRS@musicbrainz.org/ws/2/collection - server replied: Service Unavailable (QT code 301, HTTP code 503)
Picard[32534] <Notice>: E: 17:55:29 Error loading collections: Error downloading https://CrimsonKing1497:j2UyHWtUh1YJOzmtBXRS@musicbrainz.org/ws/2/collection - server replied: Service Unavailabled

**Comment by fdemmer** [comment] 2016-04-03 15:59
The requests, that are not working in your output are _not_ to last.fm. Something is trying to talk to _musicbrainz.org_. The plugin does not do that.

With that log output you probably have problems loading album information at all. The plugin is called only _after_ Picard has fetched album info from musicbrainz... without the album info the plugin cannot work.

I can't help with the musicbrainz errors, other than "try again later".

**Comment by DevonVille** [comment] 2016-04-04 09:56
Yep, the MusicBrainz errors were just it trying to load an album.
Nothing regarding the Lastfmng it seems...
Any ideas then?

**Comment by fdemmer** [comment] 2016-04-04 10:56
no, sorry. same as with #22. i can't investigate myself without a mac. afaik there aren't even virtualbox images or something i could use to debug... someone could donate me a machine ;)

**Comment by woto99** [comment] 2016-04-28 14:10
I tried again with the system date workaround and I found that it still works, but I have to set the date back to march 21 2015 (or before). Hope this can be helpful.

**Comment by fdemmer** [comment] 2016-04-28 14:14
thanks, it helps! since it is picard, that ships the python interpreter and standard library including the http/ssl handling, i think i cannot fix that in the plugin, but picard should ship with a newer python... but that is a vaguely educated guess atm.

**Comment by fdemmer** [comment] 2018-08-08 09:09
closing since picard 2 was released with python3. reopen if problem persists!

**Closed as completed by fdemmer** 2018-08-08 09:09 UTC
Labels: needs info
