### ISSUE TITLE
Scrobbling errors on OSX older version

### ISSUE THREAD

**Issue by woto99** [fdemmer/Picard-Last.fm.ng-Plugin#22] opened 2015-12-18 17:52 UTC
I've been having problems in getting lastfmng tags in the past days. Using Mac, but same problem on a fresh install on windows.
I tried also with a new apikey, but I always get this error for artists, album and tracks:

Network request error for https://ws.audioscrobbler.com/2.0/? ... : SSL handshake failed (QT code 6, HTTP code None)

**Comment by fdemmer** [comment] 2015-12-18 22:17
cannot reproduce with picard 1.3.2, plugin 0.14, windows 8.1

since it is on both your computers i suspect a network issue, proxy, firewall, temporary last.fm issue, ... something like that.

**Comment by woto99** [comment] 2015-12-19 14:17
Guessed it could be the firewall, and already tried disabling it, unfortunately it's not that.
I don't use proxies, tried also using my cell phone 4g in routing mode.
If you say it works I will try to find where the issue is.

**Comment by fdemmer** [comment] 2015-12-19 14:30
can you connect to https://ws.audioscrobbler.com/2.0/ with a browser on the computers, with the plugin issue? especially microsoft's?

what windows are you using?

i have seen such an error with servers denying the encryption used by browsers, older ssl versions and such...

i am leaving the issue open in case you/someone can gather more info.

**Comment by woto99** [comment] 2015-12-19 14:36
Both cell phone and mac connect to this page:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
-lfm status="failed"-
  -error code="6"-
    Invalid parameters - Your request is missing a required parameter
  -/error-
-/lfm-

**Comment by woto99** [comment] 2015-12-19 15:13
Ok, I tried on a third pc and it works with nothing modified in setting and ini.
I will report when I find where the problem is.
Sorry for opening this ticket.

UPDATE:
I forgot to say that the second pc was parallel, on the same mac machine, osx 10.7.2.
I think that it's something related to certificate expiration, I changed the date on my mac (setting it to 2 months ago) and scrobbling is working now. I'm a basic user so I don't know what to do. I will try updating the os.

**Comment by A45Bullet** [comment] 2016-01-07 14:11
MusicBrainz Picard Version 1.3.2
Picard-Last.fm.ng-Plugin Version 0.14
OS X Version 10.9.5 ( All Updates )

I’m getting the same error as the OP - “ Network request error SSL handshake failed (QT code 6, HTTP code None) for https://ws.audioscrobbler.com/2.0/?album=21&api_key=[USING EXISTING API KEY and a NEW API KEY]&method=album.gettoptags&artist=Adele

I can open a browser window and can open successfully https://ws.audioscrobbler.com/2.0/?album=21&api_key=[NEW API KEY]&method=album.gettoptags&artist=Adele - And a full document tree is retuned.

Installing the same versions on a PC running  Windows 7 Enterprise SP1 and connected to the same router works without issue (I didn’t update the API Key for this test)

**Comment by fdemmer** [comment] 2018-08-08 09:09
closing since picard 2 was released with python3. reopen if problem persists!

**Closed as completed by fdemmer** 2018-08-08 09:09 UTC
Labels: needs info
